[package]
name = "shortcat"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0"
shuttle-rocket = "0.45.0"
shuttle-runtime = "0.45.0"
tokio = "1.26.0"
shuttle-shared-db = { version = "0.45.0", features = ["postgres" , "sqlx" ] }
sqlx = "0.7.4"
nanoid = "0.4.0"
url = "2.5.0"
